# Generated by Django 6.0.3 on 2026-03-27 12:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowers', '0001_initial'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(max_length=5)),
                ('confidence', models.FloatField(default=0.0)),
                ('factors', models.JSONField(default=list)),
                ('bureau_score', models.IntegerField(blank=True, null=True)),
                ('dti_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('auto_approve', models.BooleanField(default=False)),
                ('scored_by', models.CharField(default='system', max_length=50)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.loanapplication')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_scores', to='borrowers.borrower')),
            ],
            options={
                'db_table': 'credit_scores',
            },
        ),
    ]
