# Generated by Django 6.0.3 on 2026-03-27 09:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branding', models.JSONField(blank=True, default=dict)),
                ('custom_domain', models.CharField(blank=True, default='', max_length=255)),
                ('product_config', models.JSONField(blank=True, default=dict)),
                ('workflow_config', models.JSONField(blank=True, default=dict)),
                ('scoring_config', models.JSONField(blank=True, default=dict)),
                ('dunning_config', models.JSONField(blank=True, default=dict)),
                ('regulatory_region', models.CharField(default='US', max_length=50)),
                ('api_key_hash', models.CharField(blank=True, default='', max_length=255)),
                ('webhook_url', models.URLField(blank=True, default='')),
                ('max_loan_amount', models.DecimalField(decimal_places=2, default=500000, max_digits=14)),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
            ],
            options={
                'db_table': 'institutions',
            },
        ),
    ]
