# Generated by Django 6.0.3 on 2026-03-27 09:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('risk_grade', models.CharField(blank=True, default='', max_length=5)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='institutions.institution')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrower_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'borrowers',
            },
        ),
        migrations.CreateModel(
            name='BorrowerProfile',
            fields=[
                ('borrower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='borrowers.borrower')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('ssn_last4', models.CharField(blank=True, default='', max_length=4)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('employment_status', models.CharField(blank=True, default='', max_length=30)),
                ('employer_name', models.CharField(blank=True, default='', max_length=255)),
                ('job_title', models.CharField(blank=True, default='', max_length=255)),
                ('annual_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monthly_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('income_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'borrower_profiles',
            },
        ),
        migrations.AddConstraint(
            model_name='borrower',
            constraint=models.UniqueConstraint(fields=('institution', 'email'), name='unique_borrower_email_per_inst'),
        ),
    ]
