# Generated by Django 6.0.3 on 2026-03-27 12:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor_type', models.CharField(default='individual', max_length=30)),
                ('accredited', models.BooleanField(default=False)),
                ('investment_preferences', models.JSONField(blank=True, default=dict)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='institutions.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investors',
            },
        ),
        migrations.CreateModel(
            name='InvestorPortfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Default Portfolio', max_length=100)),
                ('total_invested', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_returns', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('irr', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('par_30', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('par_60', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('par_90', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('default_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='institutions.institution')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='investors.investor')),
            ],
            options={
                'db_table': 'investor_portfolios',
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=14)),
                ('share_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(default='active', max_length=20)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='institutions.institution')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='loans.loan')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investors.investorportfolio')),
            ],
            options={
                'db_table': 'investments',
                'constraints': [models.UniqueConstraint(fields=('portfolio', 'loan'), name='unique_portfolio_loan')],
            },
        ),
    ]
