# Generated by Django 6.0.3 on 2026-03-27 09:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowers', '0001_initial'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('personal', 'Personal'), ('business', 'Business'), ('auto', 'Auto'), ('mortgage', 'Mortgage'), ('line_of_credit', 'Line of Credit'), ('bnpl', 'Buy Now Pay Later')], max_length=30)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('min_term_months', models.PositiveIntegerField()),
                ('max_term_months', models.PositiveIntegerField()),
                ('base_interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate_spread_by_grade', models.JSONField(blank=True, default=dict)),
                ('origination_fee_pct', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('late_fee_grace_days', models.PositiveIntegerField(default=5)),
                ('repayment_type', models.CharField(choices=[('emi', 'EMI'), ('bullet', 'Bullet'), ('balloon', 'Balloon'), ('interest_only', 'Interest Only')], default='emi', max_length=20)),
                ('requires_collateral', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='institutions.institution')),
            ],
            options={
                'db_table': 'loan_products',
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('term_months', models.PositiveIntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('purpose', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('risk_grade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=5)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('risk_factors', models.JSONField(blank=True, default=list)),
                ('approval_level', models.CharField(blank=True, default='', max_length=30)),
                ('decision_reason', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='borrowers.borrower')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='institutions.institution')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.loanproduct')),
            ],
            options={
                'db_table': 'loan_applications',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term_months', models.PositiveIntegerField()),
                ('origination_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_interest', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_payable', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outstanding_principal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('outstanding_interest', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outstanding_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('disbursement_date', models.DateField()),
                ('first_payment_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid_off', 'Paid Off'), ('delinquent', 'Delinquent'), ('defaulted', 'Defaulted'), ('restructured', 'Restructured'), ('written_off', 'Written Off')], default='active', max_length=20)),
                ('days_past_due', models.PositiveIntegerField(default=0)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='borrowers.borrower')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='institutions.institution')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan', to='loans.loanapplication')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.loanproduct')),
            ],
            options={
                'db_table': 'loans',
            },
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['institution', 'status'], name='loan_applic_institu_562972_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['borrower', 'status'], name='loan_applic_borrowe_d5aa6a_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['institution', 'status'], name='loans_institu_a50516_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['borrower', 'status'], name='loans_borrowe_6654de_idx'),
        ),
    ]
